# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: browserstack-regression

on:
  push:
    branches: [ browserstack ]
  pull_request:
    branches: [ browserstack ]
  schedule:
    - cron: "50 1 * * 1,5"

jobs:
  web-regression-browserstack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '17'

      - name: Setup selenium Grid
        run: docker-compose up -d
        
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean test site -DsuiteFile=web_regression.xml --file pom.xml
        #
        #    - name: Allure report generation
        #      run: mvn allure:report

      - name: Cleanup selenium Grid
        run: docker-compose down

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: target/allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
